# Example: ansible-playbook authorized_keys.yml -i servers_list -e 'ansible_user=user' -k
# The playbook adds an ssh key to server(s) listed
# Requires: ssh key of the origin

- name: set authorized key
  hosts: [CREATE INVENTORY FILE WITH YOUR SERVERS]

  tasks:
    - authorized_key:
        user=[USER TO CONNECT IN DESTINATION SERVER]
        state=present
        key="{{ lookup('file','[PATH OF SSH KEY]')}}"
