---
- name: Playbook to create test gce instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_email: xeme08@ansibleprojects.iam.gserviceaccount.com
    credentials_file: ansibleprojects-0770f492ec99.json
    project_id: ansibleprojects
    machine_type: n1-standard-1
    image: centos-7
  tasks:
    - name: Launch instances
      gce:
        zone: us-east1-b
        instance_names: webserver01
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"cruz_danae:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHTGVAo1/LsY5lX71qiJXeWCkQQ1ECZkRyTLk3rMKSNDGSefReUzYXfKGKPeuQljUU9DcyDiNZmW4Xnb8K1ic050SWZMJwUQ+jS/cItcnrCgZo4coMKRUCB64V2I7JygbKr6qBj1Hg0b992uYvPeqYioipOrcaJOB3VCW+zNo+PEucItfEhbelVRKYFhiFSS5onoiDormpzc7DI5zNKZ4tpLfPS4QJZNc9c/uX8nl2jdzeKrJsZwBkDbX+WJLpGfl2L/fqCzmgkLViSLZbptT3cDiFqjlL0f2vdYWCyhpnEtAJnjuXEJzUM6e15+oEsns/10euC+KrMiSJG62mAt4qj5H+GAACTud85XnzT3toLNGIHefydSDxmwEd+bx7y5DDXH+jBWJ18RaAqcsJMbtt8+esCGKXlHs6MsuU2BWTj0gFef0LO7t5eSw7R0Lhpw6i3vBJSbyp6SdS/wqd4oEXbFd8LTIlYjTWp5vgL/4/EwMOpwUbF5rB8suMIjL1rLxRgftm//KfgzHY/qwm0fHlxqCf4M6H2QqvFSY/gx5WNgQyeYvzS+aGsGYi3ktw6fcX3NLe0sGDiaEAGfOmc1IXm14zX+CVKPZNXM7lRS8t8qxDslV/LqbH9f6i5rnNBb8ZEFHh1ZWq4/J/Qj19mzoWkczHt9UM2ZEU0tZlM0504Q== xemesita@srv2.tsmx.lab"}'
