---
- name: Playbook to create load balancer on gce 
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    service_account_email: xeme08@ansibleprojects.iam.gserviceaccount.com
    credentials_file: ansibleprojects-0770f492ec99.json
    project_id: ansibleprojects

  tasks:
    - name: Create load balancer
      gce_lb:
        name: lbserver
        state: present
        region:  us-east1
        members: ['us-east1-b/wsrv01','us-east1-b/wsrv02','us-east1-b/wsrv03']
        httphealthcheck_name: hc
        httphealthcheck_port: 80
        httphealthcheck_path: "/"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
