# Example: ansible-playbook gce-rmweb.yml
# Usage: Playbook to delete web server on gce
---
- name: Playbook to delete gce instance (web server)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    service_account_email: [service_account_email]
    credentials_file: [file.json]
    project_id: [project name]
    instance_names: [YOUR VM1,VM2,VM3]

  tasks:
    - name: Delete fw rule to allow http traffic
      gce_net:
        fwname: "[NAME OF FW RULE]"
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

    - name: Delete an instance
      gce:
        zone: us-east1-b
        instance_names: "{{ instance_names }}"
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
