# Example: ansible-playbook gce-lb.yml -v
# Playbook to create load balancer on gce
# Requires: google cloud services subscription
---
- name: Playbook to create load balancer on gce
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: [service_account_email]
    credentials_file: [file.json]
    project_id: [project name]

  tasks:
    - name: Create load balancer
      gce_lb:
        name: [YOUR LOAD BALANCER NAME]
        state: present
        region:  us-east1
        members: ['us-east1-b/[YOUR MACHINE]]','us-east1-b/[YOUR MACHINE]','us-east1-b/[YOUR MACHINE]']
        httphealthcheck_name: hc
        httphealthcheck_port: 80
        httphealthcheck_path: "/"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
