# Example: ansible-playbook gce-rmlb.yml
# Usage: Playbook to delete a load balancer on gce
---
- name: Playbook to delete a load balancer on gce
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: [service_account_email]
    credentials_file: [file.json]
    project_id: [project name]

  tasks:
    - name: Delete load balancer
      gce_lb:
        name: [YOUR LOAD BALANCER NAME]
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
