# Example: ansible-playbook sat_hosts.yml
# The playbook adds server to /etc/hosts file on a list of servers
# Requires: ansible.cfg / inventory
---
- name: set hostname
  hosts: servers
  tasks:

    - name: add satellite host
      lineinfile:
        path: /etc/hosts
        line: '[IP_ADDR NAME_RESOLUTION]'
        state: present
