# Example: ansible-playbook set_ip.yml -e 'ansible_user=user'
# The playbook set an static ipv4 address
# Requires: network config template
---
- name: Set static ipv4 ip address
  hosts: servers
  tasks:
    - name: copy a new network file, backing up the original
      copy:
        src: ifcfg-ethX.txt
        dest: /etc/sysconfig/network-scripts/ifcfg-[YOUR INTERFACE]
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: restart network
      service:
        name: network
        state: restarted
