- name: Set ipv4
  hosts: servers
  tasks:
    - name: copy a new network file, backing up the original
      copy:
        src: ifcfg-ethX.txt
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        owner: root
        group: root
        mode: 0644
        backup: yes


    - name: restart network
      service:
        name: network
        state: restarted
