# Example: set_hostname.yml -e 'ansible_user=root'
# The playbook modifies the hostname according to name and ip address given
# Requires: ansible.cfg / inventory
---
- name: Set hostname
  hosts: servers
  vars:
      hostname: vm-*.tsmx.lab

  tasks:
    - name: set the hostname
      hostname: name={{ hostname.replace('*', ansible_all_ipv4_addresses[0].split('.')[3]) }}
